#!/bin/bash

if [ $# -ne 1 ]
then
    echo "ERROR: please supply version parameter, e.g. 1.5.1"
    exit 1
fi
version="$1"

git archive --format tgz --prefix=vdu_controls-$version/ HEAD > /home/michael/rpmbuild/SOURCES/vdu_controls-$version.tar.gz
