#!/bin/bash
# SPDX-FileCopyrightText: 2021-2026 Contributors to vdu_controls <https://github.com/digitaltrails/vdu_controls>
# SPDX-License-Identifier: GPL-3.0-or-later
ZIPAPP=vdu_controls.pyz
PYTHON_INTERPRETER='/usr/bin/env python3'
echo "INFO: creating executable-zip file: `pwd`/$ZIPAPP"
echo "INFO: executable-zip interpreter set to: $PYTHON_INTERPRETER"
echo "INFO: or run the zip with a specific interpreter: python3 `pwd`/$ZIPAPP"
set -x
python3 -m zipapp src -o $ZIPAPP -m vdu_controls.__main__:main -p "$PYTHON_INTERPRETER"
