#!/bin/bash
# SPDX-FileCopyrightText: 2021-2026 Contributors to vdu_controls <https://github.com/digitaltrails/vdu_controls>
# SPDX-License-Identifier: GPL-3.0-or-later
if [ $# -ne 2 ]
then
    echo "ERROR: please supply version parameter, e.g. 1.5.1 [git|local]"
    exit 1
fi

if echo $1 | grep -- '-'
then
    echo "ERROR: only a release version number is accepted, for example 2.6.5"
    exit 1
fi


version="$1"
source="$2"

if [ $source == "git" ]
then
    set -x
    git archive --format tgz --prefix=vdu_controls-$version/ HEAD > /home/michael/rpmbuild/SOURCES/vdu_controls-$version.tar.gz
    exit 0
fi

# Local source
ln -s . vdu_controls-$version
tar --exclude="__pycache__" --exclude="vdu_controls.egg-info" --exclude=".coverage" \
    --files-from=- -cvzf  /home/michael/rpmbuild/SOURCES/vdu_controls-$version.tar.gz <<EOF
vdu_controls-$version/.gitignore
vdu_controls-$version/LICENSE.md
vdu_controls-$version/MANIFEST.in
vdu_controls-$version/README.md
vdu_controls-$version/docs/_build/man/vdu_controls.1
vdu_controls-$version/docs/_build/man/vdu_controls.1.html
vdu_controls-$version/packaging/vdu_controls.wrapper
vdu_controls-$version/pyproject.toml
vdu_controls-$version/screenshots/ambient-slider-example.png
vdu_controls-$version/screenshots/Screenshot_Large-330.png
vdu_controls-$version/screenshots/Screenshot_Small-227.png
vdu_controls-$version/screenshots/Screenshot_tray-200.png
vdu_controls-$version/screenshots/Screenshot_settings-300.png
vdu_controls-$version/screenshots/presets.png
vdu_controls-$version/screenshots/lux-profiles.png
vdu_controls-$version/src/
vdu_controls-$version/translations/ar_SA.ts
vdu_controls-$version/translations/da_DK.ts
vdu_controls-$version/translations/de_DE.ts
vdu_controls-$version/translations/es_ES.ts
vdu_controls-$version/translations/fr_FR.ts
vdu_controls-$version/translations/mi_NZ.ts
vdu_controls-$version/translations/zh_CN.ts
vdu_controls-$version/sample-scripts/lux-from-webcam.bash
vdu_controls-$version/sample-scripts/lux-from-webcam.py
vdu_controls-$version/sample-scripts/vlux_meter.py
vdu_controls-$version/sample-scripts/laptop-ddcutil-emulator.bash
vdu_controls-$version/vdu_controls.desktop
vdu_controls-$version/icons/
EOF

rm vdu_controls-$version
