#!/bin/bash
# SPDX-FileCopyrightText: 2021-2026 Contributors to vdu_controls <https://github.com/digitaltrails/vdu_controls>
# SPDX-License-Identifier: GPL-3.0-or-later
mkdir -p docs/manual
cp src/vdu_controls/resources/docs/help.md docs/manual/help.md
cp README.md docs/manual/index.md
cp LICENSE.md docs/manual/LICENSE.md
cp -r screenshots docs/manual/
cp -r sample-scripts docs/manual/
cd docs
mkdocs build --site-dir _site
echo 'to test: cd docs; mkdocs serve'


