#!/bin/bash
# SPDX-FileCopyrightText: 2021-2026 Contributors to vdu_controls <https://github.com/digitaltrails/vdu_controls>
# SPDX-License-Identifier: GPL-3.0-or-later
pylupdate5 vdu_controls.py -ts translations/da_DK.ts
pylupdate5 vdu_controls.py -ts translations/de_DE.ts
pylupdate5 vdu_controls.py -ts translations/fr_FR.ts
pylupdate5 vdu_controls.py -ts translations/cs_CZ.ts
