#!/bin/bash

master_version_number=$(python3 -c 'from vdu_controls.vdu_controls.constants import VDU_CONTROLS_VERSION;print(VDU_CONTROLS_VERSION)')

base_version=$(echo $master_version_number | sed s/-.*//)

echo "INFO: master_version_number=$master_version_number base_version=$base_version"

echo "INFO: update PKGBUILD"
sed -E --in-place "s/^pkgver=[0-9.]+/pkgver=$base_version/" PKGBUILD || exit 1

echo "INFO: update setup.cfg"
sed -E --in-place "s/^version = [0-9.]+/version = $base_version/" setup.cfg || exit 1

echo "INFO: update vdu_controls.spec"
sed -E --in-place "s/^Version:( *)[0-9.]+/Version:\\1$base_version/" vdu_controls.spec || exit 1



