#!/bin/bash
# SPDX-FileCopyrightText: 2021-2026 Contributors to vdu_controls <https://github.com/digitaltrails/vdu_controls>
# SPDX-License-Identifier: GPL-3.0-or-later
for ts_file in translations/??_??.ts
do
   pylupdate6 $(find vdu_controls -name '*.py') --no-obsolete -ts $ts_file
   python3 ./utils/translate_ts.py $ts_file
done
