#!/bin/bash
# SPDX-FileCopyrightText: 2021-2026 Contributors to vdu_controls <https://github.com/digitaltrails/vdu_controls>
# SPDX-License-Identifier: GPL-3.0-or-later
for ts_file in translations/??_??.ts
do
   lrelease6 $ts_file
done
